CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(50) NOT NULL UNIQUE,
    name VARCHAR2(200) NOT NULL,
    price NUMBER(10,2) NOT NULL
);

CREATE TABLE raw_materials (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(50) NOT NULL UNIQUE,
    name VARCHAR2(200) NOT NULL,
    stock_quantity NUMBER(10,2) NOT NULL
);

CREATE TABLE product_raw_materials (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    raw_material_id NUMBER NOT NULL,
    required_quantity NUMBER(10,2) NOT NULL,

    CONSTRAINT fk_product
       FOREIGN KEY (product_id)
           REFERENCES products(id),

    CONSTRAINT fk_raw_material
       FOREIGN KEY (raw_material_id)
           REFERENCES raw_materials(id)
);

CREATE INDEX idx_prm_product ON product_raw_materials(product_id);
CREATE INDEX idx_prm_raw_material ON product_raw_materials(raw_material_id);